[package]
authors = ["David Siefert <siefert.david@gmail.com>"]
name = "webdriver-client"
version = "0.1.0"

[dependencies]
error-chain = "0.11.0"
reqwest = "0.8.5"
serde = "1.0.33"
serde_derive = "1.0.33"
serde_json = "1.0.12"
